---
- name: Create directory | "{{jira_home_dir}}"
  file: 
    path: "{{jira_home_dir}}"
    owner: "{{jira_user}}"
    group: "{{jira_user}}"
    state: directory
    
# TODO - Move this to jira role. It belongs to jira configuration instead 
# of postgres configuration.
- name: Create dbconfig.xml
  template:
    src: dbconfig.xml.j2
    dest: "{{jira_home_dir}}/dbconfig.xml"