---
- name: Create systemd service | postgresql-{{postgres_version}}
  template:
    src: "postgresql-{{postgres_version}}.service.j2"
    dest: "/usr/lib/systemd/system/postgresql-{{postgres_version}}.service"
  notify: restart postgresql service

- meta: flush_handlers

- name: Start postgresql service
  become_user: postgres
  systemd:
    name: postgresql-{{postgres_version}}
    state: started
    enabled: yes