---
- name: Install pip
  yum:
    name: python-pip 
    state: present
    update_cache: yes    
  register: pip_install

- name: Install python module psycopg2 using pip
  pip:
    name: psycopg2
    state: latest
  register: psycopg2_install
  when: pip_install is not changed

- name: Create database[{{jira_db_name}}]
  become_user: postgres
  postgresql_db:
    name: "{{jira_db_name}}"
    encoding: UTF-8
    template: template0
  when: psycopg2_install is success

- name: Create postgres user[{{jira_db_user}}]
  become_user: postgres
  postgresql_user:
    name: "{{jira_db_user}}"
    password: "{{jira_db_passwd}}"
  when: psycopg2_install is success

- name: Ensure access for user[{{jira_db_user}}]
  become_user: postgres
  postgresql_privs:
    db: "{{jira_db_name}}"
    role: "{{jira_db_user}}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE,CONNECT
  when: psycopg2_install is success