---
- name: Install python-psycopg2
  yum:
    name: python-psycopg2
    state: latest
    update_cache: yes    
  register: psycopg2_install

- name: Create database[{{jira_db_name}}]
  become_user: postgres
  postgresql_db:
    name: "{{jira_db_name}}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
  when: 
    - psycopg2_install is success
    - not ansible_check_mode

- name: Create postgres user[{{jira_db_user}}]
  become_user: postgres
  postgresql_user:
    db: "{{jira_db_name}}"
    name: "{{jira_db_user}}"
    password: "{{jira_db_passwd}}"
  when: 
    - psycopg2_install is success
    - not ansible_check_mode

- name: Ensure access for user[{{jira_db_user}}]
  become_user: postgres
  postgresql_privs:
    db: "{{jira_db_name}}"
    role: "{{jira_db_user}}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE,CONNECT
  when: 
    - psycopg2_install is success
    - not ansible_check_mode