---
- name: Install package rpm postgresql
  yum:
    name: http://download.postgresql.org/pub/repos/yum/{{postgres_version}}/{{postgres_platform}}/{{platform_arch}}/{{rpm_package}}
    state: present

- name: Install package[{{postgres_package}}]
  yum:
    name: "{{postgres_package}}"
    state: present
    update_cache: yes
  register: package_install

- name: Check if initdb is not empty
  shell: >
    "ls /var/lib/pgsql/{{postgres_version}}/data/"
  register: db_dir

- name: Init postgresql
  become_user: postgres
  shell: >
    "/usr/pgsql-{{postgres_version}}/bin/initdb -D /var/lib/pgsql/{{postgres_version}}/data/"
  when: 
    - db_dir is defined 
    - db_dir.stdout == ""
  ignore_errors: "{{ ansible_check_mode }}"

- name: install python pip
  yum: 
    name: python-pip
    state: present

- name: Install psycopg2
  pip:
    name: psycopg2
    state: present