---
- name: Install package rpm postgresql
  yum:
    name: http://download.postgresql.org/pub/repos/yum/{{postgres_version}}/{{postgres_platform}}/{{platform_arch}}/{{rpm_package}}
    state: present

# - name: Install package[{{postgres_package}}]
#   yum:
#     name: "{{postgres_package}}"
#     state: present
#     update_cache: yes