---
- name: Stop postgresql
  systemd: 
    name: "postgresql-{{postgres_version}}"
    state: stopped

- name: Configuring postgres files
  template:
    src: "{{item}}.conf.j2"
    dest: "/var/lib/pgsql/9.6/data/{{item}}.conf"
  with_items:
    - pg_hba
    - postgresql
  notify: Reboot postgresql

- name: Start postgresql
  become: yes
  systemd: 
    name: "postgresql-{{postgres_version}}"
    state: started
    enabled: yes
