---
- name: Configure Jira home directory[{{jira_home_dir}}]
  template:
    src: jira-application.properties.j2
    dest: "{{jira_install_dir}}/atlassian-jira/WEB-INF/classes/jira-application.properties"
  notify: Restart JIRA service

- name: Getting variable JAVA_HOME
  shell: >
    jrunscript -e "java.lang.System.out.println(java.lang.System.getProperty('java.home'))";
  register: system_java_home

# - name: JAVA_HOME
#   debug: msg={{system_java_home}}

- name: Setting variable JAVA_HOME
  template:
    src: setenv.sh.j2
    dest: "{{jira_install_dir}}/bin/setenv.sh"
  notify: Restart JIRA service
  when: system_java_home is defined and system_java_home.rc == 0

- name: Configure Jira server.xml
  template:
    src: server.xml.j2
    dest: "{{jira_install_dir}}/conf/server.xml"
  notify: Restart JIRA service
