---
- name: Configure Jira home directory[{{jira_home_dir}}]
  template:
    src: jira-application.properties.j2
    dest: "{{jira_install_dir}}/atlassian-jira/WEB-INF/classes/jira-application.properties"
  notify: Restart JIRA service

- name: Get JAVA_HOME
  shell: >
    jrunscript -e 'java.lang.System.out.println(java.lang.System.getProperty("java.home"));
  register: java_home_result

- name: See java JAVA_HOME
  debug:
    msg: "java_home_result"

- name: Configure JAVA_HOME
  template:
    src: jira-application.properties.j2
    dest: "{{jira_install_dir}}/atlassian-jira/"
  notify: Restart JIRA service

- name: Configure Jira server.xml
  template:
    src: server.xml.j2
    dest: "{{jira_install_dir}}/conf/server.xml"
  notify: Restart JIRA service