---
- name: Create JIRA directories
  file: 
    path: "{{item}}"
    owner: "{{jira_user}}"
    mode: 0700
    state: directory
  with_items:
    - "{{jira_install_dir}}"
    - "{{jira_home_dir}}"

- name: Download atlassian-jira-software-{{version}}.tar.gz
  get_url:
    url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{version}}.tar.gz
    dest: "/tmp/atlassian-jira-software-{{version}}.tar.gz"
  register: jira_archive

- name: Unpackage atlassian-jira-software-{{version}}.tar.gz
  unarchive:
    src: /tmp/atlassian-jira-software-{{version}}.tar.gz
    dest: /tmp
  ignore_errors: yes

- name: Copying downloaded files into {{jira_install_dir}}
  shell: mv /tmp/atlassian-jira-software-{{version}}-standalone/* {{jira_install_dir}}
  args:
    creates: "{{jira_install_dir}}/jira.installed"

- name: Set right permission to {{jira_install_dir}}
  file:
    path: "{{jira_install_dir}}"
    owner: "{{jira_user}}"
    group: "{{jira_user}}"
    state: directory
    recurse: yes