---
- name: Create JIRA directories
  file: 
    path: "{{item}}"
    owner: "{{jira_user}}"
    state: directory
  with_items:
    - "{{jira_installation}}"
    - "{{jira_home_data}}"

- name: Download atlassian-jira-software-{{version}}.tar.gz
  get_url:
    url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{version}}.tar.gz
    dest: "/tmp/atlassian-jira-software-{{version}}.tar.gz"
  register: jira_archive

- name: Unpackage atlassian-jira-software-{{version}}.tar.gz
  unarchive:
    src: /tmp/atlassian-jira-software-{{version}}.tar.gz
    dest: /tmp
  when: jira_archive.changed
  ignore_errors: yes

- name: Copying download files into {{jira_installation}}
  shell: mv /tmp/atlassian-jira-software-{{version}}-standalone/* {{jira_installation}}
  owner: "{{jira_user}}"
  when: jira_archive.changed