---
# - name: Download atlassian-jira-software-{{version}}.tar.gz
#   get_url:
#     url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{version}}.tar.gz
#     dest: /opt/atlassian-jira-software-{{version}}.tar.gz
#     owner: "{{jira_user}}"
#   register: jira_archive

# - name: Create installer directory
#   file: 
#     path: "/opt/atlassian-jira-software-{{version}}"
#     owner: "{{jira_user}}"
#     state: directory

- name: Unpackage atlassian-jira-software-{{version}}.tar.gz
  unarchive:
    src: "https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{version}}.tar.gz"
    dest: "/opt"
    owner: "{{jira_user}}"
  when: jira_archive.changed
  ignore_errors: yes
    
- name: Create JIRA directories
  file: 
    path: "{{item}}"
    owner: "{{jira_user}}"
    state: directory
  with_items:
    - "{{jira_installation}}"
    - "{{jira_home_data}}"