---
- name: Download atlassian-jira-software-{{version}}.tar.gz
  get_url:
    url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{version}}.tar.gz
    dest: /opt/atlassian-jira-software-{{version}}.tar.gz
    mode: 0400
    owner: "{{jira_user}}"
  register: jira_archive

- name: Unpackage atlassian-jira-software-8.0.2.tar.gz
  unarchive:
    src: "/opt/atlassian-jira-software-8.0.2.tar.gz"
    dest: "/opt/atlassian-jira-software-8.0.2"
    owner: jira
  when: jira_archive.changed
  ignore_erros: yes
    
# - name: Create JIRA directories
#   file: 
#     path: "{{item}}"
#     owner: "{{jira_user}}"
#     state: directory
#   with_items:
#     - "{{jira_installation}}"
#     - "{{jira_home_data}}"