---
- name: Download k3s binary
  get_url:
    url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{version}}.tar.gz
    dest: /opt/atlassian-jira-software-{{version}}.tar.gz
    mode: 0400