---
- hosts: postgres
  become: Yes
  gather_facts: Yes
  roles:
    - user
    - { role: postgresql, tags: ['psql'] }
    
- hosts: jira
  become: Yes
  gather_facts: Yes
  roles:
    - user
    - unattended_mode

- hosts: postgres
  gather_facts: Yes
  become: yes
  roles:
    - { role: jira_setup, tags: ['setup'] }
