---
- hosts: jira
  become: Yes
  gather_facts: Yes
  roles:
    - install_packages
    - jira_user
    - boostrap_jira

- hosts: postgres
  become: Yes
  gather_facts: Yes
  roles:
    - { role: posgtresql, tags: ['psql'] }
  