---
- name: Configure jira-config.properties
  template:
    src: jira-config.properties.j2
    dest: "{{jira_home_dir}}/jira-config.properties"
    owner: "{{jira_user}}"
    group: "{{jira_user}}"
    mode: 0750
  notify: Restart JIRA service