---
- name: Set JIRA user to run jira service
  template:
    src: user.sh.j2
    dest: "{{jira_install_dir}}/bin/user.sh"
    owner: "{{jira_user}}"

- name: Create systemd service
  template:
    src: jira.service.j2
    dest: /usr/lib/systemd/system/jira.service
    owner: "{{jira_user}}"
  notify: Restart JIRA service

- name: Reload systemd daemon
  meta: flush_handlers

- name: Start JIRA service
  systemd:
    name: jira
    state: started
    enabled: yes