---
- name: Create JIRA install and home directories
  file: 
    path: "{{item}}"
    owner: "{{jira_user}}"
    mode: 0700
    state: directory
  with_items:
    - "{{jira_install_dir}}"
    - "{{jira_home_dir}}"