---
- name: Set right permission to {{jira_install_dir}}
  file:
    path: "{{item}}"
    owner: "{{jira_user}}"
    group: "{{jira_user}}"
    mode: 0700
    state: directory
    recurse: yes
  with_items:
    - "{{jira_install_dir}}"
    - "{{jira_home_dir}}"