---
- name: Set right permission to JIRA directories
  file:
    path: "{{item}}"
    owner: "{{jira_user}}"
    group: "{{jira_user}}"
    mode: 0744
    state: directory
    recurse: yes
  with_items:
    - "{{jira_install_dir}}"
    - "{{jira_home_dir}}"