---
- name: Select Application Title id
  become_user: postgres
  command: "/usr/pgsql-{{postgres_version}}/bin/psql -U {{jira_db_user}} -d {{jira_db_name}} -t -c \"SELECT PE.id FROM propertyentry PE JOIN propertystring PS ON PE.id=PS.id WHERE PE.property_key = 'jira.title'\";"
  register: app_title_select_query
  retries: 3
  delay: 10
  until: app_title_select_query.rc == 0
  tags: 
    - setup

- name: Update Application Title
  become_user: postgres
  command: "/usr/pgsql-{{postgres_version}}/bin/psql -U {{jira_db_user}} -d {{jira_db_name}} -t -c \"UPDATE propertystring SET propertyvalue = '{{jira_app_title}}' WHERE id = {{app_title_select_query.stdout}}\";"
  register: app_title_update
  when: app_title_select_query.stdout != ""
  tags: 
    - setup

- name: Insert Application Title property_key
  command: "/usr/pgsql-{{postgres_version}}/bin/psql -U {{jira_db_user}} -d {{jira_db_name}} -t -c \"INSERT INTO propertyentry(id, property_key) VALUES (10100,'jira.title')\";"
  register: insert_app_title_key
  when: app_title_select_query.stdout == ""
  tags:
    - setup

- name: Insert Application Title propertyvalue
  command: "/usr/pgsql-{{postgres_version}}/bin/psql -U {{jira_db_user}} -d {{jira_db_name}} -t -c \"INSERT INTO propertystring(id, propertyvalue) VALUES (10100, '{{jira_app_title}}')\";"
  register: insert_app_title
  when: app_title_select_query.stdout == "" and insert_app_title_key is success
  tags:
    - setup

- name: Select Base Url id
  become_user: postgres
  command: "/usr/pgsql-{{postgres_version}}/bin/psql -U {{jira_db_user}} -d {{jira_db_name}} -t -c \"SELECT PE.id FROM propertyentry PE JOIN propertystring PS ON PE.id=PS.id WHERE PE.property_key = 'jira.baseurl'\";"
  register: base_url_select_query
  retries: 3
  delay: 10
  until: base_url_select_query.rc == 0
  tags: 
    - setup

- name: Update Base Url
  become_user: postgres
  command: "/usr/pgsql-{{postgres_version}}/bin/psql -U {{jira_db_user}} -d {{jira_db_name}} -t -c \"UPDATE propertystring SET propertyvalue = '{{jira_base_url}}' WHERE id = {{base_url_select.stdout}}\";"
  register: base_url_update
  when: base_url_select_query.stdout != ""
  tags: 
    - setup

- name: Insert Base Url property_key
  command: "/usr/pgsql-{{postgres_version}}/bin/psql -U {{jira_db_user}} -d {{jira_db_name}} -t -c \"INSERT INTO propertyentry(id, property_key) VALUES (10101,'jira.baseurl')\";"
  register: insert_base_url_key
  when: base_url_select_query.stdout == ""
  tags:
    - setup

- name: Insert Base Url propertyvalue
  command: "/usr/pgsql-{{postgres_version}}/bin/psql -U {{jira_db_user}} -d {{jira_db_name}} -t -c \"INSERT INTO propertystring(id, propertyvalue) VALUES (10101, '{{jira_base_url}}')\";"
  when: base_url_select_query.stdout == "" and insert_base_url_key is success
  tags:
    - setup