---
- name: Download Jira intaller atlassian-jira-software-{{version}}-x64.bin
  get_url:
    url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{version}}-x64.bin
    dest: "/tmp/atlassian-jira-software-{{version}}-x64.bin"
    mode: 0555
  register: jira_binary

- name: Create unattended install directory "{{jira_install_dir}}/.install4j
  file: 
    path: "{{jira_install_dir}}/.install4j"
    state: directory

- name: Copy response.varfile to "{{jira_install_dir}}/.install4j
  template:
    src: response.varfile.j2
    dest: "{{jira_install_dir}}/.install4j/response.varfile"

- name: Start install as Unattended mode
  # https://confluence.atlassian.com/adminjiraserver071/unattended-installation-855475683.html?_ga=2.40096363.817173845.1552928648-887595188.1549059064 
  shell: >
    ./atlassian-jira-software-{{version}}-x64.bin -q -varfile {{jira_install_dir}}/.install4j/response.varfile
  args:
    chdir: /tmp
    creates: "{{jira_install_dir}}/.install4j/installation.id"