---
- name: Download k3s binary
  get_url:
    url: "https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{version}}-x64.bin"
    dest: /opt/atlassian-jira-software-{{version}}-x64.bin
    mode: 0111